#!/bin/bash

# Parse arguments
if [ $# -eq 0 ]; then
    echo "Usage: xbatch [sbatch options] script.py"
    exit 1
fi

CMD=${*: -1}
ARGS="${@: 1:$#-1} --output=$CMD.slurm-%j.out"

# Queue job
chmod a+x $CMD
JOB=$(sbatch $ARGS -- /cvmfs/aph.gsi.de/xsuite/scripts/xlaunch $CMD)
JOB_ID=$(echo $JOB | sed -n 's/Submitted batch job \(.*\)/\1/p')
LOG="*slurm-$JOB_ID.out"
echo "$JOB"

# We are done, rest is just for convenience
#exit 0

# Show job list and status
echo ""
sleep 1
xinfo

# Show log
echo ""
echo "Now following log file, press CTRL+C to leave the job alone"
echo "tail -f $LOG"
until [ -f $LOG ]
do
  sleep 1
done
echo ""
tail -f $LOG

